app/styles/components/_footer.scss

Fix whitespace amount in footer [#127453657]

---

app/initialize.jsx
app/js/components/PageNavigation.jsx
app/js/components/PanelSwitcher.jsx
app/js/utils/Router.js
app/js/utils/build-url.js
app/js/utils/create-talent.js
app/js/utils/parse-pathname.js
app/js/utils/user-session.js
app/partials/navigation.static.hbs
package.json
tests/utils/parse-pathname.spec.js
tests/utils/user-session.spec.js

Display navigation for logged in users depending on their type

---

app.js
brunch-config.coffee

- Ensure we can run `brunch watch --server` or `npm start` with the main rails app.

Fixing brunch config to watch

---

app/js/components/PageNavigation.jsx
app/js/utils/user-session.js
tests/utils/user-session.spec.js

Fix static pages JSON & React keys

---

app.js

@jbandura Wanna take a look at this? I forgot to pass brunch watch callback in the last PR. It would never watch or recompile without the callback.

Passing brunch watch cb

---

app/initialize.jsx
app/js/utils/utm-params.js
tests/utils/utm-params.spec.js

Improvement on #29 to include cookie domain when setting a cookie

Passing current domain as default for utm cookies

---

app/pages/faq.static.hbs

Update FAQs regarding remote positions

---

app/pages/legal_notice.static.hbs

Update phone in legal

---

app/js/utils/flash-messages.js
package.json
tests/utils/flash-messages.spec.js
tests/utils/utm-params.spec.js

- visit https://staging.honeypot.io/pr-35
- execute the following in javascript console 
```javascript
document.cookie = "honeypot_flash=1; domain=.honeypot.io; expires=Thu, 01 Jan 2970 00:00:00 UTC";
```
- reload the page
- enjoy the flash message

Feature/flash message static #126965165

---

app/pages/about.static.hbs
app/partials/about_members.static.hbs

About page edits

---

app/index.html.static.hbs
app/pages/faq.static.hbs
app/pages/terms_of_service.static.hbs
app/users/sign_up.static.hbs

Sync deploy with ToS messaging

Update hiring bonus

---

app/partials/about_members.static.hbs

Add Luuk to the about page

---

app/pages/legal_notice.static.hbs

Add Emma to legal

---

app/index.html.static.hbs

Change our partners to featured partners on the LP

---

app/partials/about_members.static.hbs

https://www.pivotaltracker.com/n/projects/1474304/stories/132667623

feat(about): add andre 

---

.env.example
app/js/utils/create-invite.js
app/js/utils/data-fetcher.js
brunch-config.coffee

Staging does not use a auth code anymore so this code should not be required

Removes unused staging auth from code

---

app/pages/faq.static.hbs

Add info about referring company to FAQ
- visit the FAQ page

Include info about company referrals

---

app/partials/about_members.static.hbs

Remove Matija, Andreas & Luuk from the about page.
https://www.pivotaltracker.com/story/show/133039281

feat(about): update members

---

app/pages/for_employers_new.static.hbs

Typos in testimonials on the new company LP #135410451

---

app/js/components/PageNavigation.jsx
app/partials/navigation.static.hbs

https://github.com/honeypotio/honeypot/issues/594

Rename 'Sign in' to 'Login' for non-logged-in users #594

---

app/js/components/PageNavigation.jsx
app/partials/navigation.static.hbs
app/styles/framework/overrides/_navbar.scss

https://github.com/honeypotio/honeypot/issues/595

feat: add "Sign up" CTA  button to nav

---

app/js/components/PageNavigation.jsx
app/partials/navigation.static.hbs

[honeypot#639](https://github.com/honeypotio/honeypot/pull/639)

Rename /sign_in to /login

---

app/partials/navigation.static.hbs

Change logo from xmas

---

app/pages/legal_notice.static.hbs

Updated legal notice page with a new phone #

New Phone number for Legal page

---

s3_website.yml

https://github.com/honeypotio/honeypot/issues/634#issuecomment-271577819
https://staging.honeypot.co/pr-65/join

Redirect `/join` 👉  `lp/join`

---

app/lp/join.static.hbs

"so I ws surprised" --> "so I was surprised"
[honeypotio/honeypot/issues/772](https://github.com/honeypotio/honeypot/issues/772)

Fix typo In testimonial

---

app/js/components/JoinForm.jsx

Don't pre fill email input with query params.
https://github.com/honeypotio/honeypot/issues/794

fix(lp/join): remove email queryparams value

---

.env.example
.travis.yml
bin/deploy
brunch-config.coffee
s3_website.yml

Forward query params to redirects.
https://github.com/honeypotio/honeypot/issues/794

Forward query strings for lp/join redirect

---

.travis.yml
bin/deploy

Adds debug output to deploy script

---

README.md
app/js/components/JoinForm.jsx
app/lp/join.static.hbs

Remove tos checkbox from lp join

---

app/partials/footer.static.hbs

Autotech link to the footer

---

app/js/components/JoinForm.jsx
app/lp/join.static.hbs
app/styles/components/_talent-landing.scss

Issue:
Feature staging: https://staging.honeypot.co/pr-140/lp/join

Add signup with GitHub / Linkedin to standalone pages [#1009]

---

app/styles/components/_footer.scss

Feature staging: https://staging.honeypot.co/pr-152/pages/terms_of_service

Unnecessary white space below the main document on static pages [#653]

---

app/initialize.jsx
app/js/components/FormBase.jsx
app/js/components/InviteRequestForm.jsx
app/js/components/JoinForm.jsx
app/js/components/SignupForm.jsx
app/js/utils/error-messages.js
app/lp/de.static.hbs
app/lp/join-de.static.hbs
brunch-config.coffee
s3_website.yml

Feature staging: https://staging.honeypot.co/pr-161/lp/join-de

German landing page [#899]

---

app/js/components/JoinForm.jsx

German CTA and 'Oder' on the English /join page

---

app/partials/navigation.static.hbs
app/styles/components/_navigation.scss
app/styles/utilities/_cookie-policy.scss

Make the navigation bar sticky on our static pages [#1141]

---

app/js/components/PageNavigation.jsx
app/partials/navigation.static.hbs
app/styles/components/_navigation.scss

Only works on desktop. Mobile defaults to showing them all in the menu section.

Add a 'Company' dropdown to the navigation bar on static pages [#1178]

---

app/styles/components/_navigation.scss

- Removed the bottom border to LP pages

Join pages have a weird white line [#1266]

---

app/initialize.jsx
app/styles/components/_navigation.scss
app/styles/objects/_talent-landing.scss

Cookie info box is misplaced on the join pages [#1275]

---

app/js/components/PageNavigation.jsx
app/partials/navigation.static.hbs

Replace 'AutoTech' with 'Research' in the navigation #1280

---

app/pages/for_employers.static.hbs

closes https://github.com/honeypotio/honeypot/issues/1506

Updata acceptance rate percentage

---

app/js/components/PageNavigation.jsx
app/partials/navigation.static.hbs

- Move it from the dropdown to it's own header link
&nbsp;

Re-add Blog link to header on homepage [#1568]

---

app/pages/terms_of_service.static.hbs
package.json

Update the ToS to reflect a shorter termination period [#1601]

---

app/js/utils/create-talent.js

Try to omit credentials

---

app/partials/navigation.static.hbs

Testing: https://staging.honeypot.co/pr-445/
https://github.com/honeypotio/honeypot/issues/2108

Xmas logo [#2108]

---

app/partials/navigation.static.hbs

Testing Link: http://staging.honeypot.co/pr-474/

Remove Santabear logo [#2141]

---

app/pages/legal_notice.static.hbs
app/pages/terms_of_service.static.hbs

https://github.com/honeypotio/honeypot/issues/2599

TOS and Privacy policy update [#2599]

---

app/js/components/JoinForm.jsx
app/js/utils/create-talent.js
app/js/utils/locales.js
app/styles/components/_talent-landing.scss

You shouldn't be able to signup without having checked the ToS - including with LinkedIn/Github
Testing server: https://staging.honeypot.co/pr-592/

Add check box for ToS acceptance and update text on all signup pages [#2505]

---

app/js/components/JoinForm.jsx

GA referrer is still broken [#3166]

---

.travis.yml
package.json

Add node version

---

app/js/components/JoinForm.jsx

Fix GA check
